apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: demoapp-gateway
  namespace: canary
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - canary.test.cloudtechner.com
