apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: demoapp-gateway
  namespace: canary
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - 'canary.test.cloudtechner.com'
    port:
      name: http
      number: 80
      protocol: HTTP
