apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: example-gateway
  namespace: canary
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "canary.test.cloudtechner.com"
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - "canary.test.cloudtechner.com"
