apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: demoapp-virtualservice
  namespace: canary
spec:
  hosts:
  - canary.test.cloudtechner.com
  gateways:
  - demoapp-gateway
  http:
  - route:
    - destination:
        host: demoapp.canary.svc.cluster.local
        port:
          number: 80
