apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: example-virtualservice
  namespace: canary
spec:
  hosts:
  - "canary.test.cloudtechner.com"
  gateways:
  - example-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: demoapp.canary.svc.cluster.local
        port:
          number: 80
