apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: myapp-gateway
  namespace: canary
spec:
  selector:
    istio: ingressgateway # Ensure this is appropriate for your use case
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "a7e2cbd7a21334fbe8c7c8528bed0943-2007503.ap-south-1.elb.amazonaws.com"
